---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dohewjes/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    #- export REPOPATH=/home/dohewjes/repositories/Money-Management-System
    #- /rm -Rf ${DEPLOYPATH}_old
    #- /cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    #- /rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    #- /chmod 755 ${DEPLOYPATH}
    #- /find ${DEPLOYPATH} -type d -exec /chmod 755 '{}' \;
    #- /find ${DEPLOYPATH} -type f -exec /chmod 644 '{}' \;